server {
    listen 80;
    listen [::]:80;
    server_name portfolio.lawdigest.cloud;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name portfolio.lawdigest.cloud;

    root /var/www/portfolio.lawdigest.cloud;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/portfolio.lawdigest.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/portfolio.lawdigest.cloud/privkey.pem;

    location / {
        try_files $uri $uri/ /index.html;
    }

    access_log /var/log/nginx/portfolio.lawdigest.cloud-access.log;
    error_log /var/log/nginx/portfolio.lawdigest.cloud-error.log;
}
